AllCops:
  NewCops: enable
  TargetRubyVersion:

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashAsLastArrayItem:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
